firebase.database().ref(name12 + '/' + tosno + '/').child('PersonalInfo/').update({
    Sex:             Sex    ,                                                                        
    DoB_Day:         DoB_Day    ,                              
    DoB_Month:       DoB_Month   ,                            
    DoB_Year:        DoB_Year   ,                           
    Mobile:          Mobile     ,                      
    Handedness:      Handedness   ,                             
    Registration:    Registration  ,                               
    MotherTongue:    MotherTongue  ,                         
    Consanguinity:   Consanguinity  ,                                
    Email:           Email          ,                
    PresentAddress:  PresentAddress   ,                                 
    PermanentAddress:PermanentAddress ,                                 
    
    }); 
    firebase.database().ref(name12 + '/' + tosno + '/').child('ParentsComplaints/').update({
        PoorAttenstionSpan:PoorAttenstionSpan,
        PoorAcadamic:PoorAcadamic,
        PoorUnderstanding:PoorUnderstanding,
        StubBornBehaviour:StubBornBehaviour,
        EasyIrritability:EasyIrritability,
        Impulsivity:Impulsivity,
        Hyperactivy:Hyperactivy,
        ForgetsEasily:ForgetsEasily,
        ChangeInSleep:ChangeInSleep,
        ChangeInAppetite:ChangeInAppetite,
        Withdrawn:Withdrawn,
        Tearful:Tearful,
        LackOfConfidence:LackOfConfidence,
        Fatigue:Fatigue,
        LackOfPlayingInterest:LackOfPlayingInterest,
        Listless:Listless,
        Irritable:Irritable,
        Suicidality:Suicidality,
        StrangerAnxitility:StrangerAnxitility,
        Performance_anxity:Performance_anxity,
        StageFear:StageFear,
        SomaticComplaints:SomaticComplaints,
        generalisedAnxity:generalisedAnxity,
        BlacksOutInExam:BlacksOutInExam,
        Sleepdisturbance:Sleepdisturbance,
        OtherIssue:OtherIssue, 
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('TeachersComplaints/').update({
        PoorAttenstionSpan:PoorAttenstionSpan,
PoorAcadamic:PoorAcadamic,
PoorUnderstanding:PoorUnderstanding,
StubBornBehaviour:StubBornBehaviour,
EasyIrritability:EasyIrritability,
Impulsivity:Impulsivity,
Hyperactivy:Hyperactivy,
ForgetsEasily:ForgetsEasily,
ChangeInSleep:ChangeInSleep,
ChangeInAppetite:ChangeInAppetite,
Withdrawn:Withdrawn,
Tearful:Tearful,
LackOfConfidence:LackOfConfidence,
Fatigue:Fatigue,
LackOfPlayingInterest:LackOfPlayingInterest,
Listless:Listless,
Irritable:Irritable,
Suicidality:Suicidality,
StrangerAnxitility:StrangerAnxitility,
Performance_anxity:Performance_anxity,
StageFear:StageFear,
SomaticComplaints:SomaticComplaints,
generalisedAnxity:generalisedAnxity,
BlacksOutInExam:BlacksOutInExam,
Sleepdisturbance:Sleepdisturbance,
OtherIssue:OtherIssue,
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('SchoolHistory/').update({
        AgeOfAdmission :AgeOfAdmission,
        Standard : Standard,
        MediumOFInstruction   :MediumOFInstruction,
    FailureInEachClass       :FailureInEachClass,
    SchoolPerformance       :SchoolPerformance,
    BehaviourInSchool        :BehaviourInSchool,
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('FamilyHistory/').update({
        MentalIllness:MentalIllness,
        Psychosis:Psychosis,
        Psychosomatic:Psychosomatic,
        Neurosis:Neurosis,
        Suicide:Suicide,
        Psychopathic:Psychopathic,
        Retardation:Retardation,
        Epilepsy:Epilepsy,
        DrugAddiction:DrugAddiction,
        Enuresisinsibling:Enuresisinsibling,
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('Psyfather/').update({
        Education:Education,
        Occupation:Occupation,
        Personality:Personality,
        Traits:Traits,
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('Psymother/').update({
        Education:Education1,
        Occupation:Occupation1,
        Personality:Personality1,
        Traits:Traits1,
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('Psyothers/').update({
        Education:Education2,
        Occupation:Occupation2,
        Personality:Personality2,
        Traits:Traits2,
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('BirthAndInfancy/').update({
        PregnencySize:PregnencySize,
        IllnessPregnency:IllnessPregnency,
        WhatIlleness:WhatIlleness,
        ExposureToDrug:ExposureToDrug,
        MotherAgeWhenChildWBorn:MotherAgeWhenChildWBorn,
        HospitalDelivery:HospitalDelivery,
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('HistoryOfLabour/').update({
        DileveryType:DileveryType,
        Duration:Duration,
        Cry:Cry,
        Vaccination:Vaccination,
        BirthWeight:BirthWeight,
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('feedingHistory/').update({
        Type:Type,
        AgeofWearing:AgeofWearing,
      
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('DevelopmentHistory/').update({
        NeckHolding:NeckHolding,
        Sitting:Sitting,
        Crawling:Crawling,
        Walking:Walking,
        Running:Running,
        Cycling:Cycling,
        ObjectReached:ObjectReached,
        TransferOfObject:TransferOfObject,
        PalmarGrasp:PalmarGrasp,
        PincerGrasp:PincerGrasp,
        Handwriting:Handwriting,
        Drawing:Drawing,
        Gurgling:Gurgling,
        Babbling:Babbling,
        Monosyllable:Monosyllable,
        MeaningfulWords:MeaningfulWords,
        FluentTalking:FluentTalking,
        ClarityOfSpeech:ClarityOfSpeech,
        SocialSmile:SocialSmile,
        StrangerAnxity:StrangerAnxity,
        GroupActivity:GroupActivity,
        BladderControl:BladderControl,
        OldPreOccupation:OldPreOccupation,
        CircumscribedInterest:CircumscribedInterest,
        BowelControl:BowelControl,
        FirstProrperWordSentence :FirstProrperWordSentence   ,
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('ToiletTraining/').update({
        Bowels:Bowels,
        Bladder:Bladder,
        Punishment:Punishment
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('TemperamentalTraits/').update({
        ActivityLevel:ActivityLevel,
        Rhythmicity:Rhythmicity,
        Distractibility:Distractibility,
        Approch:Approch,
        Adaptibility:Adaptibility,
        Attention:Attention,
        Intensity:Intensity,
        Threshold:Threshold,
        Mood:Mood,
        Other:Other,
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('NeuroticTraits/').update({
        
        RidculeNT:RidculeNT,
        PrecipitatingNT:PrecipitatingNT,
        RelievingNT:RelievingNT,
        PunishmentNT:PunishmentNT,
        WettingNT:WettingNT,
        SuckingNT:SuckingNT,
        BitingNT:BitingNT,
        SleepWalkingcNT:SleepWalkingcNT,
        NightMaresNT:NightMaresNT,
        MasturbationNT:MasturbationNT,
        PicaNT:PicaNT,
        BruxismNT:BruxismNT,
        PyromaniaNT:PyromaniaNT,
        FearsNT:FearsNT,
        PhobiasNT:PhobiasNT,
        DepressionNT:DepressionNT,
        ChangeNT:ChangeNT,
        ChangeinAppetiteNT:ChangeinAppetiteNT,
        WithdrawnNT:WithdrawnNT,
        TearfulNT:TearfulNT,
        LackOfConfidenceNT:LackOfConfidenceNT,
        FatigueNT:FatigueNT,
        LackOfInterestPlayNT:LackOfInterestPlayNT,
        ListlessNT:ListlessNT,
        SuicidalityNT:SuicidalityNT,
        OtherNT:OtherNT,
        TreatmentNT:TreatmentNT,
        DetailsNT:DetailsNT,
        AnxityNT:AnxityNTMain,
        StrangerNT:StrangerNT,
        StrangerDetailsNT:StrangerDetailsNT,
        PerformanceNT:PerformanceNT,
        PerformanceDetailsNT:PerformanceDetailsNT,
        StageNT:StageNT,
        StageDetailsNT:StageDetailsNT,
        PhobiasNT:PhobiasNT,
        PhobiasDetailsNT:PhobiasDetailsNT,
        PanicNT:PanicNT,
        PanicDetailsNT:PanicDetailsNT,
        ObsessiveNT:ObsessiveNT,
        ObsessiveDetailsNT:ObsessiveDetailsNT,
        ComplaintsNT:ComplaintsNT,
        ComplaintsDetailsNT:ComplaintsDetailsNT,
        GeneralisedNT:GeneralisedNT,
        GeneralisedDetailsNT:GeneralisedDetailsNT,
        BlacksNT:BlacksNT,
        BlacksDetailsNT:BlacksDetailsNT,
        DistrubanceNT:DistrubanceNT,
        DistrubanceDetailsNT:DistrubanceDetailsNT,
        AppetiteNT:AppetiteNT,
        AppetiteDetailsNT:AppetiteDetailsNT,
        TraitsNT:TraitsNTThe,
        temperNT:temperNT,
        companyNT:companyNT,
        BlamesNT:BlamesNT,
        resentfulNT:resentfulNT,
        arguesNT:arguesNT,
        DeliberatelyNT:DeliberatelyNT,
        AnnoyedNT:AnnoyedNT,
        vindictiveNT:vindictiveNT,
        DdisordersNT:DdisordersNTTheMMainPart,
        AggressionNT:AggressionNT,
        BulliesNT:BulliesNT,
        ThreatenNT:ThreatenNT,
        FightsNT:FightsNT,
        CrueltyNT:CrueltyNT,
        DestructionNT:DestructionNT,
        ViolationNT:ViolationNT,
      
      });

      firebase.database().ref(name12 + '/' + tosno + '/').child('PastHistory/').update({
        CNSDisease:CNSDisease,
        SystemicDisease :SystemicDisease,
        Psychomaticillness:Psychomaticillness,
        Hospitalisation:Hospitalisation,
        Psychiatricillness:Psychiatricillness,
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('Behaviour/').update({
        Hyperactivity :Hyperactivity,
        Active :Active,
        Lethargic :Lethargic,
        Overtalkactiver :Overtalkactiver,
        Silent :Silent,
        Obedient :Obedient,
        Disobedient :Disobedient,
        DisobedientOther :DisobedientOther,
        DisobedientOtherDetails :DisobedientOtherDetails,
        Normal :Normal,
        Good :Good,
        Poor :Poor,
        Average :Average,
        AverageOther :AverageOther,
        AaverageOtherDetails :AaverageOtherDetails,
        Willingnesstogo :Willingnesstogo,
        notwillingWhatIs :notwillingWhatIs,
        OtherOfWhatIs :OtherOfWhatIs,
        childabsentisism :childabsentisism,
        FrequencyOfabsentisism :FrequencyOfabsentisism,
        theirattitude :theirattitude,
        theirattitudeOther  :theirattitudeOther              ,
      
      });
      firebase.database().ref(name12 + '/' + tosno + '/').child('ClinicalExamination/').update({
        consciousnessCE :consciousnessCE,
        operativeCE :operativeCE,
        OrientationCE :OrientationCE,
        TimeCE :TimeCE,
        PlaceCE :PlaceCE,
        PersonCE :PersonCE,
        BuiltCE :BuiltCE,
        NutritionCE :NutritionCE,
        BMICE :BMICE,
        AnaemiaCE :AnaemiaCE,
        CyanosisCE :CyanosisCE,
        JaurdiceCE :JaurdiceCE,
        LymphCE :LymphCE,
        ClubbingCE :ClubbingCE,
        OedemaCE :OedemaCE,
        PulseCE :PulseCE,
        RespirationCE :RespirationCE,
        RateCE :RateCE,
        RhythmCE :RhythmCE,
        TypeCE :TypeCE,
        DepthCE :DepthCE,
        TemperatureCE :TemperatureCE,
        PressureCE :PressureCE,
        DeforminityCE :DeforminityCE,
        DetailsCE :DetailsCE,
        CardiovascularCE :CardiovascularCE,
        S1CE :S1CE,
        S2CE :S2CE,
        MurmursCE :MurmursCE,
        RespiratoryCE :RespiratoryCE,
        AdventitiousCE :AdventitiousCE,
        NervousCE :NervousCE,
        ToneCE :ToneCE,
        PowerCE :PowerCE,
        ReflexesCE :ReflexesCE,
        CerebellarCE :CerebellarCE,
        InvoluntaryCE :InvoluntaryCE,
        CoordinateCE :CoordinateCE,
        NeirologicalCE :NeirologicalCE,
        diadokokinesiaCE :diadokokinesiaCE,
        balancingCE :balancingCE,
        ApraxiaCE :ApraxiaCE,
        GraphaestesiaCE :GraphaestesiaCE,
        coordinationCE :coordinationCE,
        VisionCE :VisionCE,
        HearingCE :HearingCE,
        AppearanceCE :AppearanceCE,
        TidyCE :TidyCE,
        TidyDetailsCE :TidyDetailsCE,
        UntidyCE :UntidyCE,
        UntidyDetailsCE :UntidyDetailsCE,
        InappropraitelyCE :InappropraitelyCE,
        InappropraitelyDetailsCE :InappropraitelyDetailsCE,
        behaviourCE :behaviourCE,
        behaiviordetailsCE :behaiviordetailsCE,
        ExaminerCE :ExaminerCE,
        AffectiveCE :AffectiveCE,
        AppropraitnessCE :AppropraitnessCE,
        SpeechCE :SpeechCE,
        SpeechDetailsCE :SpeechDetailsCE,
        AttentionCE :AttentionCE,
        AttentionDetailsCE :AttentionDetailsCE,
        MoodCE :MoodCE,
        ProductivityCE :ProductivityCE,
        RelevantCE :RelevantCE,
        CoherantCE :CoherantCE,
        ContentCE :ContentCE,
        PreoccupationCE :PreoccupationCE,
        PreoccupationDetailsCE :PreoccupationDetailsCE,
        DelusionCE :DelusionCE,
        DelusionDetailsCE :DelusionDetailsCE,
        IdeasCE :IdeasCE,
        IdeasvDetailsCE :IdeasvDetailsCE,
        OtherDCE :OtherDCE,
        DetailsOtherCE :DetailsOtherCE,
        MotorCoordinateCE :MotorCoordinateCE,
        MotorInvoluuntaryCE :MotorInvoluuntaryCE,
        MotorActivityCE :MotorActivityCE,
        OrientationTimeCE :OrientationTimeCE,
        OrientationPlaceCE :OrientationPlaceCE,
        OrientationPersonCE :OrientationPersonCE,
        OrientationMemoryCE :OrientationMemoryCE,
        OrientationImmediateCE :OrientationImmediateCE,
        OrientationRecentCE :OrientationRecentCE,
        OrientationPostCE :OrientationPostCE,
        OrientationRemoteCE :OrientationRemoteCE,
        GeneralCE :GeneralCE,
        SpecificCE :SpecificCE,
        AbstractCE :AbstractCE,
        AbstractDetailsCE :AbstractDetailsCE,
        JudgementTestCE :JudgementTestCE,
        JudgementSocialCE :JudgementSocialCE,
        InsightCE  :InsightCE                ,
      
      });